[package]

name        = "memoirs_mac" 
version     = "0.1.1"
authors     = [ "Charlie Lipford <charlie.lipford.code@gmail.com>" ]
description = "Memoization functions for Rust"
repository  = "https://github.com/Inspiravetion/Memoirs"
readme      = "../README.md"
keywords    = ["Memoization", "SmartFunction"]
license     = "MIT"

[dev-dependencies]

lazy_static = "0.1.1"
memoirs     = "0.1.1"

[lib]
name       = "memoirs_mac"
plugin     = true
crate-type = ["dylib"]